version: '3'

services: 

  app:
    build: 
      context: node
    container_name: app
    image: sivellifc/node
    networks: 
      - node-network
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh node index.js
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    healthcheck:
      test: mysql -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD --execute "select 1"

  nginx:
    build: 
      context: ./nginx
    image: sivellifc/nginx-node
    container_name: nginx-node
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - app
   

networks: 
  node-network:
    driver: bridge      
